export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_COUNTRIES_PENDING = 'REQUEST_COUNTRIES_PENDING';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAILED = 'REQUEST_COUNTRIES_FAILED';

export const REQUEST_COUNTRY_VALUES = 'REQUEST_COUNTRY_VALUES';

export const OPEN_DAILOG = 'OPEN_DAILOG';
export const CLOSE_DAILOG = 'CLOSE_DAILOG';

